Day 2 code - ppo,sac,ddpg
rl-education/kims pull request #11
Opened 2023-05-14 11:46 UTC by limjiyoon

## Changes?
- PPO, SAC, DDPG solution 코드 추가

Future work
- Problem 코드 추가
- Visualize 추가
- Requirements.txt 보완

2023-05-16 13:20 UTC, yurirocha15 reviewed
As a general comment, most of the functions are missing docstrings.

2023-05-16 13:20 UTC, yurirocha15 commented on src/day_2/ppo/requirements.txt
Shouldn't this file be inside `src/day2`?

2023-05-19 16:28 UTC, dongminlee94 requested changes

2023-05-19 16:28 UTC, dongminlee94 commented on src/day_2/ddpg/solution/ddpg.py
> +"""
ddpg의 경우 한 파일에 너무 몰려있는 것 같은데요. 쪼개서 두면 어떨까요? 예를들면, replay buffer 따로 network 따로 ddpg 따로 이렇게요

2023-05-19 16:28 UTC, dongminlee94 commented on src/day_2/ddpg/solution/ddpg.py
> +    def __init__(self, capacity):
```suggestion
    def __init__(self, capacity: int):
```

모든 코드에 type annotation을 표기하면 좋을 것 같은데 어떠신가요~?

2023-05-19 16:28 UTC, dongminlee94 commented on src/day_2/ddpg/solution/ddpg.py
> +        return np.clip(action + ou_state, self.low, self.high)
OU Noise를 빼고 간단히 아래와 같이 action에 noise를 주는 것으로 대체하면 어떨까요? 
```python
act_noise = 0.1
action = action + act_noise * np.random.randn(act_dim)
```

생각보다 강의할 때 이런 것들이 시간도 많이 잡아먹기도 하고, 강의할 때는 간단한게 최고라고 생각합니다 ㅎㅎ

2023-05-19 16:28 UTC, dongminlee94 commented on src/day_2/ppo/solution/ppo.py
> +        num_actions = self.env.action_space.shape[1]  # type: ignore
```suggestion
        state_dim = self.env.observation_space.shape[1]
        num_actions = self.env.action_space.shape[1]
```

linting이 없어서 빼고 될 것 같습니다.

2023-05-19 16:28 UTC, dongminlee94 commented on src/day_2/ppo/solution/ppo.py
> +            next_state, reward, terminate, truncate, _ = env.step(action)
gym 버전 0.23.1이면 `truncate, _`이 아니라 `done`이지 않나요?

2023-05-19 16:28 UTC, dongminlee94 commented on src/day_2/ddpg/solution/ddpg.py
> +        return actions
이 부분은 어디에 쓰이나요?

2023-06-04 12:32 UTC, limjiyoon commented on src/day_2/ddpg/solution/ddpg.py
> +        return np.clip(action + ou_state, self.low, self.high)
Done.

2023-06-04 12:33 UTC, limjiyoon commented on src/day_2/ddpg/solution/ddpg.py
> +        return actions
지웠습니다

2023-06-13 12:24 UTC, yurirocha15 approved these changes
I will approve with one question: Why there are so many reinforce files? Are you going to use all of them? If not, I think it would be better to remove the files you won't use to avoid confusion.

2023-06-13 12:24 UTC, yurirocha15 commented on src/day_2/ddpg/ddpg.py
> +    """Replay buffer for SAC."""
```suggestion
    """Replay buffer for DDPG."""
```

2023-06-13 12:24 UTC, yurirocha15 commented on src/day_2/ddpg/solution/ddpg.py
>      """Replay buffer for SAC."""
```suggestion
    """Replay buffer for DDPG."""
```

2023-06-13 12:46 UTC, limjiyoon commented on src/day_2/ddpg/ddpg.py
> +    """Replay buffer for SAC."""
> I will approve with one question: Why there are so many reinforce files? Are you going to use all of them? If not, I think it would be better to remove the files you won't use to avoid confusion.

I will use all of them.

1) Naive Implementation
2) Batch
3) Baseline
4) Apply to Pendulum

I would add number to the files to avoid confusion.

2023-06-13 14:17 UTC, merged